# Generated by Django 2.1.7 on 2019-04-27 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('type', models.CharField(choices=[('01', 'ลากิจ'), ('02', 'ลาป่วย')], default='01', max_length=2)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('approve_status', models.CharField(choices=[('10', 'รอการอนุมัติ'), ('11', 'อนุมัติ'), ('12', 'ไม่อนุมัติ')], default='10', max_length=3)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
